# Generated by Django 4.1.7 on 2023-04-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPersonel', models.CharField(max_length=20)),
                ('PrePersonel', models.CharField(max_length=50)),
                ('Responsable', models.BooleanField(default=False)),
                ('NumTelPersonnel', models.CharField(max_length=10)),
                ('RefDirection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.direction')),
            ],
        ),
    ]
