# Generated by Django 4.1.7 on 2023-04-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LibVille', models.CharField(max_length=30, unique=True)),
                ('RefRegion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
        ),
    ]
