# Generated by Django 4.1.7 on 2023-04-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marque', '0001_initial'),
        ('direction', '0001_initial'),
        ('typemateriel', '0001_initial'),
        ('bureau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAcquisition', models.DateField()),
                ('DesiMateriel', models.CharField(max_length=20, null=True)),
                ('NumSerMateriel', models.CharField(max_length=20, null=True)),
                ('CaractMateriel', models.CharField(max_length=50, null=True)),
                ('Observation', models.TextField(max_length=255, null=True)),
                ('Statut', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('RefBureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bureau.bureau')),
                ('RefDirection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.direction')),
                ('RefMarque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marque.marque')),
                ('RefTypeMateriel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='typemateriel.typemateriel')),
            ],
        ),
    ]
