# Generated by Django 4.1.7 on 2023-04-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='Precision',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='DesiMateriel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
