# Generated by Django 4.1.7 on 2023-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0002_materiel_precision_alter_materiel_desimateriel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='CaractMateriel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='DateAcquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='NumSerMateriel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
