# Generated by Django 4.1.7 on 2023-04-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='Besoins',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='TotalEmploye',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
