# Generated by Django 4.1.7 on 2023-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_direction_besoins_direction_totalemploye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='LibAbbDirection',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
