# Generated by Django 4.1.7 on 2023-04-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etat', '0001_initial'),
        ('panne', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RemIntervention', models.CharField(max_length=255, null=True)),
                ('TachEffectue', models.CharField(max_length=255)),
                ('DatDebIntervention', models.DateTimeField()),
                ('DatFinIntervention', models.DateTimeField()),
                ('RefEtat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etat.etat')),
                ('RefPanne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panne.panne')),
                ('RefPersonnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel')),
            ],
        ),
    ]
